### ISSUE TITLE
integration points CI CD

### ISSUE THREAD

**Issue by leonardotorresaltez** [factorhouse/kpow#14]
Does Kpow offer a rest api in order to integrate its features to Continuous Integration pipelines?

**Comment by wavejumper** [comment]
Hi @leonardotorresaltez this is the next major feature we are bringing to Kpow: REST API for Gitops/CI. This will include a Terraform module.

I'll leave this ticket open so that I can update you on the progress. 
FYI we are not sure whether this feature will be placed in our paid product or included in our community edition yet.

**Comment by d-t-w** [comment]
Hi @leonardotorresaltez,

Kpow v93.1 introduces an OpenAPI 3.1 REST API to control Kafka, Schema, and Connect resources.

https://factorhouse.io/blog/releases/93-1/

The API is currently only included in the commercial version of our product (not the community edition) but if you would like to try it out you can sign up for a trial here: https://factorhouse.io/kpow/get-started/
