### ISSUE TITLE
Unable to connect to Kafka Cluster

### ISSUE THREAD

**Issue by ghost** [factorhouse/kpow#17]
**Version of Kpow**
The version of Kpow you are running

**Describe the issue**
A clear and concise description of the issue
<img width="897" alt="Screenshot 2023-09-14 at 12 48 01 PM" src="https://github.com/factorhouse/kpow/assets/144885848/198c473e-9f25-4e57-b67c-262cf806da4d">

**Additional context**
I have used the same into to connect to other UI but KPOW isn't able to connect.  Kafka 2.13 3.5.1 is running locally

**Comment by d-t-w** [comment]
Hello,

You are running Kafka on localhost, presumably in Docker (or Docker Compose).

You are also running Kpow in Docker. 

The bootstrap "127.0.0.1:9092" is most likely trying to connect to localhost within the Kpow docker container, rather than on the "host" localhost. This is a class local docker networking issue.

You can find more information about docker networking here:

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

One approach is to run Kpow on the same docker network as Kafka, something similar to:

```
--network compose_default
```

Or you can try connecting to a bootstrap with "host.docker.internal:9092" instead of "127.0.0.1:9092", much of this depends on how you're running Kafka locally.
